// Code generated by mdatagen. DO NOT EDIT.

package filter

import (
	"errors"
)

// Config config configures the matching behavior of a Filter.
type Config struct {
	// Filter using a simple wildcard pattern. Accepted wildcard characters are `?` (single character wildcard) and `*` (n-character wildcard). All other regex characters (such as `.`, common in OpenTelemetry metric names) are treated as literals when using this pattern.
	Pattern string `mapstructure:"pattern"`
	// Filter using a Go regex.
	Regexp string `mapstructure:"regexp"`
	// Filter using a literal string.
	Strict string `mapstructure:"strict"`
	// prevent unkeyed literal initialization
	_ struct{}
}

// Validate validates the Config fields according to schema annotations.
func (c *Config) Validate() error {
	var err error

	if inner_err := validateConfig(c); inner_err != nil {
		err = errors.Join(err, inner_err)
	}

	return err
}
